[package]
name = "hcl-ffi"
version = "0.0.1"
edition = "2024"
license = "CC0 OR MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hashicorp-configuration-language-rs = { path = ".." }
serde_json = { version = "1.0.151", default-features = false, features = ["std"] }

[build-dependencies]
cbindgen = { version = "0.28", default-features = false }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin)', 'cfg(tarpaulin_include)'] }
