[package]
name = "hcl-macros"
version = "0.0.1"
edition = "2024"
authors = ["Samuel Marks"]
license = "CC0 OR MIT OR Apache-2.0"
repository = "https://github.com/SamuelMarks/hashicorp-configuration-language-rs"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", default-features = false, features = ["derive", "parsing", "clone-impls", "proc-macro", "printing", "full", "extra-traits", "visit"] }
quote = { version = "1.0", default-features = false, features = ["proc-macro"] }
proc-macro2 = { version = "1.0", default-features = false, features = ["proc-macro"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin)', 'cfg(tarpaulin_include)'] }
