[package]
name = "hcl-lsp"
version = "0.0.1"
edition = "2024"
authors = ["Samuel Marks"]
license = "CC0 OR MIT OR Apache-2.0"
repository = "https://github.com/SamuelMarks/hashicorp-configuration-language-rs"

[dependencies]
hashicorp-configuration-language-rs = { path = ".." }
serde = { version = "1.0.229", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.151", default-features = false, features = ["std"] }
derive_more = { version = "2.1.1", default-features = false, features = ["display", "error", "from"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin)', 'cfg(tarpaulin_include)'] }
