[package]
name = "hashicorp-configuration-language-rs-fuzz"
version = "0.0.1"
publish = false
edition = "2024"
authors = ["Samuel Marks"]
license = "CC0 OR MIT OR Apache-2.0"
repository = "https://github.com/SamuelMarks/hashicorp-configuration-language-rs"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version = "0.4", default-features = false }
arbitrary = { version = "1.3", default-features = false, features = ["derive"] }

[dependencies.hashicorp-configuration-language-rs]
path = ".."

[[bin]]
name = "parse"
path = "fuzz_targets/parse.rs"

[[bin]]
name = "eval"
path = "fuzz_targets/eval.rs"

[[bin]]
name = "msgpack"
path = "fuzz_targets/msgpack.rs"

[[bin]]
name = "hcl1"
path = "fuzz_targets/hcl1.rs"

[[bin]]
name = "hcl-testdata"
path = "fuzz_targets/hcl_testdata.rs"
